name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0

      - name: Restore dependencies
        run: dotnet restore ./NetNinja.Serializers.Tests/NetNinja.Serializers.Tests.csproj

      - name: Build
        run: dotnet build ./NetNinja.Serializers.Tests/NetNinja.Serializers.Tests.csproj --no-restore --configuration Release

      - name: Run tests
        run: dotnet test ./NetNinja.Serializers.Tests/NetNinja.Serializers.Tests.csproj --no-build --verbosity normal