name: .NET CI Pipeline

on:
  push:
    branches:
      - master  
  pull_request:
    branches:
      - master  

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0 
      
      - name: Restore dependencies
        run: dotnet restore
        working-directory: './NetNinja.Serializers'
        env:
          DOTNET_ROOT: /usr/share/dotnet
      
      - name: Build NetNinja.Serializers
        run: dotnet build --configuration Debug
        working-directory: './NetNinja.Serializers'
      
      - name: Build NetNinja.Serializers.Tests
        run: dotnet build --configuration Debug
        working-directory: './NetNinja.Serializers.Tests'
      
      - name: Run Tests
        run: dotnet test --no-build --configuration Debug --verbosity normal
        working-directory: './NetNinja.Serializers.Tests'